name: Metrics
on:
  # Runs every day at 5am (see https://crontab.guru/#0_5_*_*_*)
  schedule:
    - cron: '0 5 * * *'
  
  # Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_SECRET }}
          
          user: vtwoptwo
          commits_authoring: vtwoptwo, vtuptu, vprohaska
          config_timezone: Europe/Madrid
          template: terminal

          base: activity
          base_indepth: yes
          repositories: 1000
          repositories_batch: 2
          repositories_affiliations: owner, collaborator, organization_member

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
